name: easycanchas2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets: 
   - assets/clases.png
   - assets/clubes.png
   - assets/deportes.png
   - assets/match.png
   - assets/prime.png
   - assets/favs.png
   - assets/bci.png
   - assets/tenis.png
   - assets/padel.png
   - assets/futbolito.png
   - assets/techado.png
   - assets/clinica.png
   - assets/babyfut.png
   - assets/futbol.png
   - assets/raquetbol.png
   - assets/multicancha.png
   - assets/multitech.png
   - assets/squash.png
   - assets/splash.png


  fonts:
   - family: Inter
     fonts:
       - asset: fonts/Inter-VariableFont_slnt,wght.ttf