name: easycanchas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true



  assets: 
   - assets/1.png
   - assets/2.png
   - assets/3.png
   - assets/4.png
   - assets/5.png
   - assets/6.png
   - assets/7.png
   - assets/8.png
   - assets/clases.png
   - assets/clubes.png
   - assets/deportes.png
   - assets/match.png
   - assets/prime.png
   - assets/favs.png
   - assets/bci.png
   - assets/splash.png
   - assets/tenis.png
   - assets/padel.png
   - assets/futbolito.png
   - assets/techado.png
   - assets/clinica.png
   - assets/babyfut.png
   - assets/futbol.png
   - assets/raquetbol.png
   - assets/multicancha.png
   - assets/multitech.png
   - assets/squash.png
   - assets/calendario.png




  fonts:
   - family: Inter
     fonts:
       - asset: fonts/Inter-VariableFont_slnt,wght.ttf
   
   
   

splashscreen: ^1.3.0
